### PR TITLE
Enhancement update document sharing modal to pull from contacts list (#573)

### LINKED ISSUE #573: Enhancement: Update document sharing modal to pull from contacts list
### Describe the Current Behavior/Feature:
Currently, to share a document with someone, you must enter their pod URL. This is hard for users because it requires them to remember the Pod URL of everyone they want to share with. Conceptually it is incorrect as well, because you do not share with a pod, you share with a Web ID 
image

### Proposed Behavior/Feature:
Rework the sharing modal to share with people off their contact list. This can use the same functionality as currently exists in the messaging system (a dropdown that searches the contact's first and last name).
image

### Additional context:
This may require removing logic around adapting the "pod url." This logic is unnecessary. If we have a person's web Id, we can use it directly.

### PR DESCRIPTION
**Pull request by joshua-cornett**
## This PR:
Resolves #573
 
**1.** Document sharing (SetAclPermissionsModal) uses Web ID instead of Pod URL   
**2.** Populates a dropdown of contacts and associated Web IDs
**3.** _Side improvement_: Header of FormSection no longer overflows

## Screenshots:

image

image

image

image

image

### CODE REVIEW

File: src/components/Form/FormSection.jsx [hunk 1]
```diff
@@ -27,7 +27,8 @@ const FormSection = ({ title, headingId, children }) => (
       alignItems: 'center',
       mx: '3px',
       padding: '16px',
-      minWidth: '50%'
+      minWidth: '50%',
+      maxWidth: '75vdw'
```
Comment (leekahung) [inline src/components/Form/FormSection.jsx]: Minor thing, but I believe you mean the `dvw` unit here for device viewport width?

File: src/components/Modals/SetAclPermissionsModal.jsx [hunk 2]
```diff
@@ -107,8 +123,8 @@ const SetAclPermissionsModal = ({ showModal, setShowModal, dataset }) => {
           dataset.modalType === 'container' ? 'Share All Documents' : `Share ${dataset.docName}`
         }
       >
-        <form onSubmit={handleAclPermission} autoComplete="off">
-          <FormControl required fullWidth sx={{ marginBottom: '1rem' }}>
+        <form onSubmit={handleAclPermission} autoComplete="off" style={{ width: '100%' }}>
+          <FormControl required fullWidth sx={{ maxWidth: '75vdw', marginBottom: '1rem' }}>
```
Comment (leekahung) [inline src/components/Modals/SetAclPermissionsModal.jsx]: Same unit here, think it should be `dvw` instead of `vdw`.

File: src/components/Modals/SetAclPermissionsModal.jsx [hunk 3]
```diff
@@ -39,16 +40,27 @@ import useNotification from '../../hooks/useNotification';
...
     permissionType: ''
   });
   const [processing, setProcessing] = useState(false);
 
+  const { data } = useContactsList();
+  const contactListOptions = data?.map((contact) => ({
+    label: `${contact.person} ${contact.webId}`,
+    id: contact.webId
+  }));
+  const shareeName = data?.filter(
```
Comment (leekahung) [inline src/components/Modals/SetAclPermissionsModal.jsx]: Double `e` in variable name, should be `shareName`

File: src/components/Modals/SetAclPermissionsModal.jsx [hunk 4]
```diff
@@ -125,28 +141,34 @@ const SetAclPermissionsModal = ({ showModal, setShowModal, dataset }) => {
...
+          <Autocomplete
+            id="set-acl-to"
+            name="setAclTo"
+            data-testid="newShareWith"
+            sx={{ marginBottom: '1rem' }}
+            freeSolo
+            fullWidth
+            required
+            autoFocus
+            value={shareeName?.person ?? permissionState.webIdToSetPermsTo}
```
Comment (leekahung) [inline src/components/Modals/SetAclPermissionsModal.jsx]: Double `e` in variable name, should be `shareName`

**Review by leekahung — COMMENTED** [review]
Very minor issues, think it should be good to go after they're addressed

File: src/components/Modals/SetAclPermissionsModal.jsx (hunk 3 above)
Comment (joshua-cornett) [reply src/components/Modals/SetAclPermissionsModal.jsx]: That was intentional, though I'm not sure if sharee is _actually_ a word haha. Meant it as the person being shared with. For readability though I'll make it shareName either way.

File: src/components/Modals/SetAclPermissionsModal.jsx (hunk 2 above)
Comment (joshua-cornett) [reply src/components/Modals/SetAclPermissionsModal.jsx]: Ah, good catch

**Comment by joshua-cornett** [comment]
> Very minor issues, think it should be good to go after they're addressed

Understood, taking care of it now - thanks for reviewing!

File: src/components/Modals/SetAclPermissionsModal.jsx (hunk 3 above)
Comment (leekahung) [reply src/components/Modals/SetAclPermissionsModal.jsx]: I see, sharee like mentee, got it. No problem. 👍

File: src/components/Modals/SetAclPermissionsModal.jsx [hunk 5]
```diff
@@ -125,28 +141,34 @@ const SetAclPermissionsModal = ({ showModal, setShowModal, dataset }) => {
...
+            sx={{ marginBottom: '1rem' }}
+            freeSolo
+            fullWidth
+            required
+            autoFocus
+            value={shareName?.person ?? permissionState.webIdToSetPermsTo}
+            disablePortal
+            autoSelect
+            options={contactListOptions}
+            onChange={(event, newValue) => {
```
Comment (leekahung) [inline src/components/Modals/SetAclPermissionsModal.jsx]: I don't think `event` is used here.

If that's the case, we could replace this with an `_`, `_event`, or `_e` to keep things consistent with the other event parameters that's used in event calls.

File: src/components/Modals/SetAclPermissionsModal.jsx [hunk 6]
```diff
@@ -125,28 +141,34 @@ const SetAclPermissionsModal = ({ showModal, setShowModal, dataset }) => {
...
+              setPermissionState({
+                ...permissionState,
+                webIdToSetPermsTo: newValue.id ?? newValue
+              });
+            }}
+            placeholder={permissionState.podUrlToSetPermissionsTo}
+            error={permissionState.podUrlToSetPermissionsTo === podUrl}
```
Comment (leekahung) [inline src/components/Modals/SetAclPermissionsModal.jsx]: The state `permissionState` in line 47 don't have the values `podUrlToSetPermissionsTo` set to them. I believe it's supposed to be `webIdToSetPermsTo` now that podUrl got updated to webIds.

As for the placeholder, I don't think we need that anymore since we could just use the text from renderInput, which is "WebID to share with" and the text itself is pretty helpful.

Comment (leekahung) [reply src/components/Modals/SetAclPermissionsModal.jsx]: As for Line 164, the condition should be `permissionState.webIdToSetPermissionsTo === webId` since the webId would never equal podUrl, the error condition would never be triggered for the field.

**Review by leekahung — COMMENTED** [review]
Seem to have missed a few other things the first time around (apologize for the slip), but this really should be it. In case, I've missed something, I've turned on the `@ts-check` flag locally just to make sure.

**Comment by leekahung** [comment]
> > Very minor issues, think it should be good to go after they're addressed
> 
> Understood, taking care of it now - thanks for reviewing!

Hey Josh, thanks for bearing with me! Just a few more things, but I've made sure this time that it really should be good to go.

**Comment by joshua-cornett** [comment]
Ah I see, not sure how I missed those. I'll take a look and get them sorted.

File: src/components/Modals/SetAclPermissionsModal.jsx (hunk 5 above)
Comment (joshua-cornett) [reply src/components/Modals/SetAclPermissionsModal.jsx]: I opted for _

File: src/components/Modals/SetAclPermissionsModal.jsx (hunk 6 above)
Comment (joshua-cornett) [reply src/components/Modals/SetAclPermissionsModal.jsx:164]: - renderInput isn't defined until the component is rendered, so I hardcoded `placeholder={"WebID to share with"}`

Comment (joshua-cornett) [reply src/components/Modals/SetAclPermissionsModal.jsx]: > The state `permissionState` in line 47 don't have the values `podUrlToSetPermissionsTo` set to them. I believe it's supposed to be `webIdToSetPermsTo` now that podUrl got updated to webIds.
> 
> As for the placeholder, I don't think we need that anymore since we could just use the text from renderInput, which is "WebID to share with" and the text itself is pretty helpful.

- renderInput isn't defined until the component is rendered, so I hardcoded `placeholder={"WebID to share with"}`

**Comment by joshua-cornett** [comment]
Should be set, re-requesting review

**Review by leekahung — APPROVED** [review]
Nice changes! It looks good to me, approving.

**Comment by leekahung** [comment]
I'll have this PR merged into the development branch. 👍
