### PR TITLE
Issue 406/PASS logo production bug

### LINKED ISSUE #406: PASS Logo in Navbar not showing in Production
### Bug Title: PASS Logo in Navbar not showing in Production

---
### Bug Description:

The production build for PASS is not showing the static asset of the PASS logo. It's likely due to the image not being sourced properly with Vite.

---
### Expected Behavior:
To show the PASS Logo

---
### Screenshots (If applicable):

Screen Shot 2023-09-11 at 1 12 07 (2)

---
### Possible Solution (optional):

Going to try a solution involving the creation of a `public` directory where we can store assets for production. (see The `public` directory section of https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url)

### PR DESCRIPTION
**Pull request by leekahung**
## Issue 406/PASS logo production bug

---
## This PR:
**1.**    Fixes bug for image assets in production build (I've checked a local build `npm run build` with output at `/dist` then served the website locally with `npx serve dist` to see if assets did indeed render for the website)
**2.**   Re-routed all path to the logo to the new location in `/public`

---
### Components
- `/src/components/NavBar/NavbarDesktop.jsx`
- `/src/components/NavBar/NavbarLoggedOut.jsx`
- `/src/components/NavBar/NavbarMobile.jsx`

### Other Files
- `/README.md`
- `/index.html`
- `/src/assets/pass-logo.png` moved to `/public/pass-logo.png`

---
## Screenshots (if applicable):

Existing build in Development:

https://github.com/codeforpdx/PASS/assets/14917816/b1576ff2-fafb-411c-9eb9-a12d0a53bd10

Branch with bug fix:

https://github.com/codeforpdx/PASS/assets/14917816/4748b2bb-0c8a-493e-9ae7-ff5e09ce8ad8

### CODE REVIEW

**Review by xscottxbrownx — APPROVED** [review]

File: src/components/NavBar/NavbarLoggedOut.jsx [hunk 1]
```diff
@@ -21,12 +21,7 @@ const NavbarLoggedOut = () => (
     <AppBar position="static" color="primary">
       <Toolbar sx={{ minHeight: '64px' }}>
         <Link to="/">
-          <img
-            src="src/assets/pass-logo.png"
-            alt="logo"
-            style={{ marginRight: '2rem' }}
-            aria-label="logo"
-          />
+          <img src="/pass-logo.png" alt="logo" style={{ marginRight: '2rem' }} aria-label="logo" />
```
Comment (leekahung) [inline src/components/NavBar/NavbarLoggedOut.jsx:24]: Prettier being Prettier, I guess. This line was under the 100 character limit.
