### PR TITLE
Issue #615 refetch if null

### LINKED ISSUE #615: [Bug Report] - Civic Profile Submission
### Describe the bug:

Currently, been trying to get information added to the Civic Profile. However, I'm currently getting errors with regards to that functionality (see clip below).

### Expected behavior:

Was expecting to let users update housing information from the submission forms and update the relevant TTL file in the back.

### Screenshots:

https://github.com/codeforpdx/PASS/assets/14917816/7e3338fa-0a76-44e8-b90a-8229bdf724c7

### To Reproduce:
1. Go to "Civic Profile"
2. Insert information for form
3. Click on "Submit" button

### Possible Fix:

Checking existing functionality for adding information onto Solid and updating the function if needed

### PR DESCRIPTION
**Pull request by JaeGif**
## This PR:
Resolves #615 

Issue seems to be that useRdfCollection's storedDocument is occasionally null when the mutation is called. My quick workaround is to add a useEffect that forces a refetch (and therefore a new state of storedDocument) if storedDocument is null. 
 
## Additional Context (optional):
This feels a little hacky to me but I'm not familiar enough with the codebase yet to figure out a different way. A new set of eyes/feedback is appreciated.

### CODE REVIEW

File: src/hooks/useRdfCollection.js [hunk 1]
```diff
@@ -70,6 +70,7 @@ const useRdfCollection = (parse, serialize, fileUrl, fetchData) => {
   const addMutation = useMutation({
     mutationFn: async (item) => {
       if (!data) await fetchDocument();
+      // HERE
```
Comment (leekahung) [inline src/hooks/useRdfCollection.js]: Think we could remove this comment now that we found where to debug the problem.

**Review by leekahung — APPROVED** [review]
Just minor feedback on the debug comment, but the feature is working again! Good work! Can approve for merging

File: src/hooks/useRdfCollection.js (hunk 1 above)
Comment (JaeGif) [reply src/hooks/useRdfCollection.js]: Yep my bad forgot I left it in honestly 😅

**Comment by leekahung** [comment]
Hold on, make sure you format and lint the files before merging.

**Comment by JaeGif** [comment]
> Hold on, make sure you format and lint the files before merging.

Whoops, must've been removing the new line in the gh editor. Will fix in a moment.
