### PR TITLE
 fixed linting errors, resolved issue

### LINKED ISSUE #572: Enhancement: Remove Username from contacts, update required fields
### Describe the Current Behavior/Feature:
Currently we have a field, username, that we require for every contact list added. This is a holdover from an early iteration of PASS, and isn't needed. Today it confuses more than it helps. We also currently require a first name and last name when creating a contact.

### Proposed Behavior/Feature:
Remove the username field from PASS contacts, and make the first name and last name no longer required. The username is a concept that is not particularly applicable to Solid. People are identified by Web IDs, not usernames. The Web ID is what we need to record.

We also don't need to enforce the first name or last name. As long as the person has the web ID, they can create a contact. If they don't have the web ID, they can't create the contact - the logic we have around the contact entry won't run without it. So we can remove those required fields. They're useful, but not necessary.

The new fields on Contacts should be:

- Web ID: required
- First Name: optional
- Last Name: optional

### Rationale:
We want to keep PASS simple. Adding multiple different kinds of identifiers like username and webId to the system confuses more than it helps.

### PR DESCRIPTION
**Pull request by fighawkins**
## This PR:
Resolves #572 
 
**1.**    Removed username field and its associated traces from contact list related files. 
**2.** Changed first name and last name fields from required to optional. 
**3.** commented out renderWebId function, as it used username in creating a url. i did not delete in case we want to repurpose.

## Screenshots (if applicable):
Screenshot 2024-02-06 at 9 53 27 PM
here is a screenshot of the data table as is currently displayed. I am curious if we need/want the webId included in the rows, as right now it is not included in the displayed data, though is being stored and can be seen upon visiting the profile for that contact.

### CODE REVIEW

File: src/components/Contacts/ContactListTable.jsx [hunk 1]
```diff
@@ -107,8 +107,8 @@ const ContactListTable = ({ contacts, deleteContact }) => {
         columns={columnTitlesArray}
         rows={contacts?.map((contact) => ({
           id: contact.webId,
-          'First Name': contact.givenName,
-          'Last Name': contact.familyName,
+          'First Name': contact.givenName || 'N/A',
+          'Last Name': contact.familyName || 'N/A',
```
Comment (leekahung) [inline src/components/Contacts/ContactListTable.jsx]: Rather than N/A, think it's fine if we leave it as an empty string

File: src/components/Modals/AddContactModal.jsx [hunk 2]
```diff
@@ -48,59 +47,45 @@ const AddContactModal = ({ addContact, showAddContactModal, setShowAddContactMod
   const { addNotification } = useNotification();
   const [userGivenName, setUserGivenName] = useState('');
   const [userFamilyName, setUserFamilyName] = useState('');
-  const [username, setUsername] = useState('');
```
Comment (leekahung) [inline src/components/Modals/AddContactModal.jsx:51]: While it's true that we don't need a "username" for identifying a user, I think usernames can be an optional field that'll be beneficial for first-time/early users of PASS. The `renderWebId` function can be repurposed for that case.

There would be quirks for sure (especially if the formatting for webId is different or if the solid server is different), but I think the webId can be rectified with direct/subsequent communication between the two users especially if we're able to edit the contact list, not just read, add, and delete.

File: src/components/Modals/AddContactModal.jsx [hunk 3]
```diff
@@ -118,11 +103,11 @@ const AddContactModal = ({ addContact, showAddContactModal, setShowAddContactMod
               margin="normal"
               id="add-user-given-name"
               name="addUserGivenName"
-              label="First/given name"
+              label="First/given name (Optional)"
               autoComplete="given-name"
               value={userGivenName}
               onChange={(e) => setUserGivenName(e.target.value)}
-              required
+              required={false}
```
Comment (leekahung) [inline src/components/Modals/AddContactModal.jsx]: With MUI, you could drop `required` from the attributes, it's equivalent to `required="false"`

File: src/components/Modals/AddContactModal.jsx [hunk 4]
```diff
@@ -131,24 +116,14 @@ const AddContactModal = ({ addContact, showAddContactModal, setShowAddContactMod
...
-          <TextField
-            margin="normal"
-            id="add-username"
-            name="addUsername"
-            label="Username"
-            autoComplete="username"
-            value={username}
-            onChange={(e) => wrappedSetUsername(e.target.value)}
-            required
+            required={false}
```
Comment (leekahung) [inline src/components/Modals/AddContactModal.jsx]: Same as the other `<TextField>`, you could drop `required` from the attributes to make this optional.

File: src/components/Contacts/ContactListTable.jsx
Comment (leekahung) [inline src/components/Contacts/ContactListTable.jsx:1]: With `Person` no longer in use and `First Name` and `Family Name` being optional, we should replace the message that appears when attempting to delete a contact from the list. For the time being, the changes will return `null` (see clip). 

https://github.com/codeforpdx/PASS/assets/14917816/9b7a97ee-7aee-4d24-b2c6-997d93b6052f

You can still delete the contact (it doesn't break functionality), but we can fix the wording by replacing `null` with `webId` or if `First Name` and/or `Family Name` exists, utilize those (you could use the same approach you did with `nameDisplay` in `src/components/Modals/AddContactModal.jsx`, but with the data pulled from Solid instead of a local variable). I believe the element/component for the confirmation modal is in the Contacts page itself?

File: src/components/Modals/AddContactModal.jsx [hunk 5]
```diff
@@ -48,59 +47,45 @@ const AddContactModal = ({ addContact, showAddContactModal, setShowAddContactMod
...
+
     const { addUserGivenName, addUserFamilyName, addWebId } = event.target.elements;
+
     const userObject = {
-      givenName: addUserGivenName.value.trim(),
-      familyName: addUserFamilyName.value.trim(),
-      webId: addWebId.value.trim()
+      webId: addWebId.value.trim(),
+      ...(addUserGivenName.value.trim() && { givenName: addUserGivenName.value.trim() }),
+      ...(addUserFamilyName.value.trim() && { familyName: addUserFamilyName.value.trim() })
```
Comment (leekahung) [inline src/components/Modals/AddContactModal.jsx]: I think `addUserGivenName.value.trim()` and `addUserFamily.value.trim()` would still be "truthy" even without the `.trim()`.

The lines could be simplified to:

```javascript
      ...(addUserGivenName.value && { givenName: addUserGivenName.value.trim() }),
      ...(addUserFamilyName.value && { familyName: addUserFamilyName.value.trim() })
```

File: src/components/Modals/AddContactModal.jsx [hunk 6]
```diff
@@ -48,59 +47,45 @@ const AddContactModal = ({ addContact, showAddContactModal, setShowAddContactMod
...
-    }
-
-    try {
       await addContact(userObject);
-      addNotification(
-        'success',
-        `"${userObject.givenName} ${userObject.familyName}" added to contact list`
-      );
+      const nameDisplay =
+        [userObject.givenName, userObject.familyName].filter(Boolean).join(' ') || 'Contact';
```
Comment (leekahung) [inline src/components/Modals/AddContactModal.jsx]: We can use the `webId` instead of a generic "Contact" as `nameDisplay`

**Review by leekahung — CHANGES_REQUESTED** [review]
I've taken a look over the changes you have made to the contacts list. Nice work!

Got some feedback on the changes. There are also unit tests breaking (I've haven't touched on those), but think we could have those updated here too after addressing some of the feedback.

About additional columns to the contacts list, I agree we'll probably want to include `webId` if First Name and Last Name would no longer be required. Otherwise, it'll be difficult to see who that person is (N/A or blank depending on how we wish to display empty values) outside of clicking one of the interactive icons in the same row. At that point, we'll probably want to sort by `webId`.

File: src/components/Modals/AddContactModal.jsx (hunk 6 above)
Comment (fighawkins) [reply src/components/Modals/AddContactModal.jsx]: Thanks! I'm happy to get to work addressing these. Before I do, I just want to confirm, you do want to re-introduce username? as an optional field. I know the issue was straightforward about wanting it removed. There definitely some quirks going on here for sure.

Comment (fighawkins) [reply src/components/Modals/AddContactModal.jsx]: also, i've gotten the delete confirmation and notification to display the webid instead of the person, but would we want maybe to program some logic so that the messages display a name or combo of names if there are any, but will display web id if there are no names? or are we happy with it just displaying the webId?

Comment (leekahung) [reply src/components/Modals/AddContactModal.jsx]: > Thanks! I'm happy to get to work addressing these. Before I do, I just want to confirm, you do want to re-introduce username? as an optional field. I know the issue was straightforward about wanting it removed. There definitely some quirks going on here for sure.

Yeah, I think it'll be beneficial as an optional field. But we could leave leave this removed if we want to follow the issue.

Comment (leekahung) [reply src/components/Modals/AddContactModal.jsx]: > also, i've gotten the delete confirmation and notification to display the webid instead of the person, but would we want maybe to program some logic so that the messages display a name or combo of names if there are any, but will display web id if there are no names? or are we happy with it just displaying the webId?

Yes, that's correct. Either the webid when there's no names available or just the name themselves when they are.

Comment (fighawkins) [reply src/components/Modals/AddContactModal.jsx]: okay, i've pushed the changes, and I believe it is all addressed and taken care of.

I did leave the username field out for now, as I think we should go over this section in a meeting a get a consensus, or at least get wilfreds input, as it was his issue I believe. There are some ux/ui developments that could still be made in the section as a whole, would be good to workshop it. 

Lastly, I'm noticing the test is failing still, I'm curious what is going on, but I don't have much experience with running these kinds of tests. Would love to know what I should do differently, or what I can learn from this, thanks!

File: .github/workflows/ci.yml
Comment (leekahung) [inline .github/workflows/ci.yml:1]: Think we should have the CI process use the same version on Node PASS uses via .nvmrc, which is Node 18

File: src/components/Modals/AddContactModal.jsx (hunk 6 above)
Comment (leekahung) [reply src/components/Modals/AddContactModal.jsx]: Because of the the functional and component changes, the unit tests are failing since it's likely testing for things that were removed or altered.

I recommend starting with the tests files with the same name as the components and hooks and look/read up on tutorials or reaourcess for basic unit tests with jest or vitest like https://medium.com/@masbagaspn/unit-testing-react-application-with-vitest-and-react-testing-library-910f6f4dc675 

Think that should give you a head start

Comment (fighawkins) [reply src/components/Modals/AddContactModal.jsx]: okay. I believe I've correctly rewritten the tests based on the changed functionality implemented in the contact list, but I am new to this process so let me know if everything looks good. thanks!

File: src/pages/Contacts.jsx [hunk 7]
```diff
@@ -35,17 +35,27 @@ const Contacts = () => {
...
   const { addNotification } = useNotification();
 
+  const getContactDisplayName = (contact) => {
+    if (!contact) {
+      return 'Unknown Contact';
+    }
+
+    const { givenName, familyName, webId } = contact;
+    const name = [givenName, familyName].filter(Boolean).join(' ');
+    return name || `Web ID: ${webId}`;
```
Comment (leekahung) [inline src/pages/Contacts.jsx]: For this, just the `webId` should be enough if the name is not given. Don't think we would need the extra `Web ID: ` string as part of it.

File: .eslintrc.js [hunk 8]
```diff
@@ -10,17 +10,11 @@ module.exports = {
...
-  ],
-  extends: [
-    'plugin:react/recommended',
-    'airbnb',
-    'prettier',
-    'plugin:jsdoc/recommended'
-  ],
+  globals: {
+    expect: 'readonly'
+  },
```
Comment (leekahung) [inline .eslintrc.js]: I'm not sure what this is trying to fix?

File: test/components/Modals/AddContactModal.test.jsx [hunk 9]
```diff
@@ -1,7 +1,7 @@
 import React from 'react';
 import { render, screen } from '@testing-library/react';
 import userEvent from '@testing-library/user-event';
-import { describe, expect, it, vi } from 'vitest';
+import { describe, it, vi } from 'vitest';
```
Comment (leekahung) [inline test/components/Modals/AddContactModal.test.jsx]: I'm confused as to why `expect` has been removed. It's a core function from `vitest` that we're using to validate the unit tests, include this back in.

File: test/components/Modals/AddContactModal.test.jsx [hunk 10]
```diff
@@ -47,7 +47,7 @@ describe('add contact', () => {
   const inputData = {
     givenName: 'given  ',
     familyName: '  family',
-    username: '  username  '
+    webId: '  webId ' // Changed 'username' to 'webId'
```
Comment (leekahung) [inline test/components/Modals/AddContactModal.test.jsx]: The extra comment can be removed

File: src/components/Contacts/ContactListTable.jsx [hunk 11]
```diff
@@ -107,11 +115,12 @@ const ContactListTable = ({ contacts, deleteContact }) => {
...
-          'Last Name': contact.familyName,
-          Profile: contact,
-          Message: contact,
-          Delete: contact
+          'First Name': contact.givenName || '',
+          'Last Name': contact.familyName || '',
+          webId: contact.webId,
+          Profile: contact, // Ensure this is rendered as intended
+          Message: contact, // Verify handleSendMessage uses correct data
+          Delete: contact // Check deleteContact logic
```
Comment (leekahung) [inline src/components/Contacts/ContactListTable.jsx]: The extra comments could be removed. If need to be kept, they should be on the logic and functions that processes `contact`

File: test/components/Modals/AddContactModal.test.jsx [hunk 12]
```diff
@@ -60,18 +60,18 @@ describe('add contact', () => {
...
-    const username = screen.getByRole('textbox', { name: 'Username' });
+    const givenName = screen.getByRole('textbox', { name: 'First/given name (Optional)' });
+    const familyName = screen.getByRole('textbox', { name: 'Last/family name (Optional)' });
+    const webIdInput = screen.getByPlaceholderText('WebId');
     const submitButton = screen.getByRole('button', { name: 'Add Contact' });
 
     await user.type(givenName, inputData.givenName);
     await user.type(familyName, inputData.familyName);
-    await user.type(username, inputData.username);
+    await user.type(webIdInput, inputData.webId); // Updated to use 'webId' instead of 'username'
```
Comment (leekahung) [inline test/components/Modals/AddContactModal.test.jsx]: Extra comment here can be removed

File: test/components/Modals/AddContactModal.test.jsx [hunk 13]
```diff
@@ -87,18 +87,18 @@ describe('add contact', () => {
...
```
Comment (leekahung) [inline test/components/Modals/AddContactModal.test.jsx]: Extra comment here is not needed, can be removed

File: test/components/Modals/AddContactModal.test.jsx [hunk 14]
```diff
@@ -112,7 +112,7 @@ describe('add contact', () => {
     expect(userObject).toMatchObject({
       givenName: inputData.givenName.trim(),
       familyName: inputData.familyName.trim(),
-      webId: expect.stringContaining(inputData.username.trim())
+      webId: expect.stringContaining(inputData.webId.trim()) // Updated to use 'webId' instead of 'username'
```
Comment (leekahung) [inline test/components/Modals/AddContactModal.test.jsx]: Comment here is not needed

File: test/hooks/useContactsList.test.jsx [hunk 15]
```diff
@@ -53,7 +53,7 @@ describe('useContactsList', () => {
     givenName: 'Zoro',
     familyName: 'Roronoa',
     webId: 'http://www.example.com/swords',
-    person: 'Zoro Roronoa',
+    person: null,
```
Comment (leekahung) [inline test/hooks/useContactsList.test.jsx]: Given that `person` would no longer be in use, rather than changing this to `null`, the line itself can be removed entirely.

File: test/components/Modals/AddContactModal.test.jsx (hunk 9 above)
Comment (fighawkins) [reply test/components/Modals/AddContactModal.test.jsx]: Hey, I can see how it may look confusing, but expect is still being used in the test. That also answers your other question. except is a global function, and so does not need imported explicitly in each file. the test is still running and passing with except, doing the same thing.

I can change it back if you'd like, it's not a problem.

File: test/hooks/useContactsList.test.jsx (hunk 15 above)
Comment (leekahung) [reply test/hooks/useContactsList.test.jsx]: Also, given the fact that you've updated the function that serializes the Solid object/Thing, the function that makes the mock Thing from Line 42 to Line 49 needs to be updated to match the new changes (see the changes you've done for the `serialize` function in `src/hooks/useContactsList.js` hook and replace the function inside `makeIntoThing` with that new function). You could keep the name as `makeIntoThing` if you'd like

File: .eslintrc.js [hunk 16]
```diff
@@ -10,17 +10,11 @@ module.exports = {
...
+  plugins: ['react', 'prettier', 'jsdoc'],
+  extends: ['plugin:react/recommended', 'airbnb', 'prettier', 'plugin:jsdoc/recommended'],
```
Comment (leekahung) [inline .eslintrc.js:14]: I don't think this file needs to be reformatted

File: .eslintrc.js (hunk 8 above)
Comment (leekahung) [reply .eslintrc.js]: It looks like it's related to the `expect` function from `vitest` and ignores those errors if added. That's not needed in this case, we can revert this change back.

File: test/components/Modals/AddContactModal.test.jsx (hunk 9 above)
Comment (leekahung) [reply test/components/Modals/AddContactModal.test.jsx]: This should be changed back. What the unit tests are using is the `expect` function from `vitest` specifically (https://vitest.dev/api/expect). It can't be used it if not imported from `vitest` itself. There are no global version of vitest's `expect` which takes in assertions from `chai` (https://www.chaijs.com/)

File: test/hooks/useContactsList.test.jsx (hunk 15 above)
Comment (fighawkins) [reply test/hooks/useContactsList.test.jsx]: okay, i've made another request addressing all of these. I apologize if it has been sloppily done. Thanks for your time kahung

Comment (leekahung) [reply test/hooks/useContactsList.test.jsx]: No worries Fig, it's what reviews are for, to weed out things someone might have missed. I, for one, think you're doing just fine.

File: .eslintrc.js (hunk 16 above)
Comment (leekahung) [reply .eslintrc.js:14]: Think I'll just resolve this

Doesn't affect the codebase linter

**Review by leekahung — APPROVED** [review]
Alright! Think this is ready to go from my end. I can approve this.

@Jared-Krajewski @andycwilliams @timbot1789

**Review by timbot1789 — APPROVED** [review]

**Comment by timbot1789** [comment]
Looks Good! Feel free to merge it whenever you want.

**Comment by leekahung** [comment]
Hey @fighawkins! Just to let you know that this PR looks good for merging. Was wondering if there's still anything you'd think still needs to be gone over.

**Comment by fighawkins** [comment]
okay, I apologize for this, but there was a conflict that needed resolved before it would let me merge, so I attempted to take care of it but now it is showing a check not passing, having to do with prettier. I'm a little unsure of how to take care of it, so just checking in

**Comment by leekahung** [comment]
Looks like Prettier picked up a formatting issue post-conflict resolution. The extra empty line in `AddContactModal.tsx` should be pretty easy to take care of. You can either do it manually or with `npm run prettier:run`. After that, just push the changes.

Screenshot 2024-02-20 at 11 17 05 AM
