### PR TITLE
Use `getByRole` where appropriate and improve some test magic numbers

### LINKED ISSUE #449: Enhancement: Use `getByRole` or `testId` in tests over `getByLabelText`
### Describe the Current Behavior/Feature:

We currently have tests that use `getByLabelText` in the tests when other selector methods would suffice.

### Proposed Behavior/Feature:

We should convert `getByLabelText` tests to something less fragile like `getByRole/TestId`.

### Rationale:

Relying on `LabelText` for anything other than rare cases where it is necessary make tests fragile and possibly can imply that adding labels is the way to select elements.

Using `getByRole` in particular can also reinforce testing of functionality. For instance, in testing that a button maintains the expected accessible name, selecting it via `Role` of `button` helps reinforce that we are indeed selecting for a button, whereas selecting by `LabelText` can result in a false positive if the element loses the `button` role. This could help stop significant accessibility regressions.

Because label texts can change but functionality should change much more seldom, this also makes maintenance of the tests much easier.

### Proposed Implementation (if applicable):

For instances where selecting by role is applicable, do so. 

In instances where that doesn't work, giving elements a `data-testid` will give some of the same benefits and not rely so much on implementation details.

### Example of existing test

```diff
it('renders NavbarLoggedOut when user is not logged in', () => {
-    const { getByLabelText } = render(
+    const { getByRole } = render(
       <SessionContext.Provider value={{ session: { info: { isLoggedIn: false } } }}>
         <BrowserRouter>
           <NavBar />
         </BrowserRouter>
       </SessionContext.Provider>
     );
-    const loginButton = getByLabelText('Login Button');
+    const loginButton = getByRole('button');

     expect(loginButton).not.toBeNull();
   });
```

See https://testing-library.com/docs/queries/byrole/ for more info on more specific selection using the `name` option.

### PR DESCRIPTION
**Pull request by milofultz**
Resolves #449 
 
**1.** Uses `getByRole` where appropriate and updates components with appropriate roles where missing.
**2.** Removed some "magic" variables in tests.

### CODE REVIEW

File: src/components/NavBar/NavbarDesktop.jsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ const NavbarDesktop = ({ setShowConfirmation }) => {
           </Link>
           <NavbarLinks aria-label="navigation links" />
           <Box sx={{ flexGrow: 1 }} />
-          <Box aria-label="menu" sx={{ display: { xs: 'none', md: 'flex' } }}>
+          <Box sx={{ display: { xs: 'none', md: 'flex' } }} role="group">
```
Comment (milofultz) [inline src/components/NavBar/NavbarDesktop.jsx:72]: Label isn't required, as each link will be announced when tabbed into it and `menu` doesn't provide other meaningful info.

File: test/components/Contacts/ContactsListTable.test.jsx [hunk 2]
```diff
@@ -68,5 +68,5 @@ it('sorts clients by familyName', () => {
   const client1 = getByRole('cell', { name: 'Zeigler' });
   const client2 = getByRole('cell', { name: 'Builder' });
 
-  expect(client1.compareDocumentPosition(client2)).toBe(2);
+  expect(client1.compareDocumentPosition(client2)).toBe(Node.DOCUMENT_POSITION_PRECEDING);
```
Comment (milofultz) [inline test/components/Contacts/ContactsListTable.test.jsx:71]: https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition

File: test/components/NavBar/NavBar.test.jsx [hunk 3]
```diff
@@ -30,31 +30,31 @@ describe('resize tests', () => {
...
+    const { getByRole } = render(
       <SessionContext.Provider value={{ session: { info: { isLoggedIn: true } } }}>
         <BrowserRouter>
           <NavBar />
         </BrowserRouter>
       </SessionContext.Provider>
     );
 
-    const iconMenu = getByLabelText('menu');
+    const iconMenu = getByRole('group');
```
Comment (xscottxbrownx) [inline test/components/NavBar/NavBar.test.jsx:41]: Is there something that by default has a role of group? I'm not seeing anything directly expressed as such.

This is a learning question for me, not questioning this logic.

File: test/components/NavBar/NavbarMobile.test.jsx [hunk 4]
```diff
@@ -6,15 +6,15 @@ import NavbarMobile from '../../../src/components/NavBar/NavbarMobile';
...
+  const { queryByRole } = render(
     <BrowserRouter>
       <NavbarMobile />
     </BrowserRouter>
   );
 
   const logo = queryByRole('img', { name: /logo$/ });
-  const navLinks = queryByLabelText('navigation tabs');
-  const hamburgerMenu = queryByLabelText('mobile menu');
+  const navLinks = queryByRole('tablist');
```
Comment (xscottxbrownx) [inline test/components/NavBar/NavbarMobile.test.jsx:16]: Same question here... curious where this role is found - or if it's a default of MUI tabs?

File: test/pages/Signup.test.jsx [hunk 5]
```diff
@@ -49,8 +49,8 @@ describe('Signup Page', () => {
         }
       }
     };
-    const { getByText } = render(<MockSignupContexts session={sessionObj} />);
-    expect(getByText('Register for PASS', { exact: false })).not.toBeNull();
+    const { getByRole } = render(<MockSignupContexts session={sessionObj} />);
+    expect(getByRole('heading')).not.toBeNull();
```
Comment (xscottxbrownx) [inline test/pages/Signup.test.jsx]: And this works because either component that can be rendered have a heading?  If that is true, is that too generic of a test?

**Review by xscottxbrownx — COMMENTED** [review]
Questions to help my understanding...

**Review by timbot1789 — APPROVED** [review]
LGTM! I like PRs that remove more code than they add.

File: test/components/NavBar/NavBar.test.jsx (hunk 3 above)
Comment (milofultz) [reply test/components/NavBar/NavBar.test.jsx:41]: Unfortunately, nothing has a `group` role by default. `div`'s are often used for grouping, but are otherwise devoid of any native `role`.

File: test/components/NavBar/NavbarMobile.test.jsx (hunk 4 above)
Comment (milofultz) [reply test/components/NavBar/NavbarMobile.test.jsx:16]: Yeah this is part of the [React tabs MUI component](https://mui.com/material-ui/react-tabs/). I was digging around looking to see if roles were applied and found it with the accessibility inspector in Firefox.

Screen Shot 2023-11-14 at 7 31 41 PM

File: test/pages/Signup.test.jsx (hunk 5 above)
Comment (milofultz) [reply test/pages/Signup.test.jsx]: True, I should probably add a `name` option to this to make it more specific. Thanks!

Comment (milofultz) [reply test/pages/Signup.test.jsx]: Got it in there 👍
