### PR TITLE
Issue 377/private profile info and Issue 387 fixing profile bug

### LINKED ISSUE #377: Create inputs for private profile information
### Feature Description:
In PASS, the user's profile utilizes the public profile to fill out the "Profile" page. There could be certain things that should remain private such as date of born, mailing address, etc. As such, we need to create a separate file that stores the user's profile information that's not under "/profile" on Solid and have them available to fill out by the user in their "Profile" page on PASS.

Allowing case workers to view this information via permissions could be done separately in a follow-up issue/PR.

---
### Proposed Solution:
Create a privateProfileInfo.ttl somewhere in `/PASS` (perhaps in a new Profile container, i.e. `/PASS/Profile`).

### LINKED ISSUE #387: Profile fails to load client info correctly due to incorrect parameters
### Bug Description:
At the moment, the Profile page utilizes the `client` state when passing through React Router to generate the other user's profile information. However, it's been recently changed to `contact`. The Profile page and relevant components would need to be updated.

---
### Possible Solution (optional):
Update Profile page and relevant components to use `contact` instead of `client`. Considering PR #379 is currently working to update the page, we could include the corrections there.

### PR DESCRIPTION
**Pull request by leekahung**
## Create Private Profile Information on User's pod

---
## This PR:
**1.**    Generates a new `Profile` container (in /PASS) with a `privateProfile.ttl` (this container is separate from the public /profile container)
**2.**   A new ACL file will be set for Profile; a follow-up PR will be created to account for permission adjustments
**3.**   Including a single new field for the profile card using information from `privateProfile.ttl` as proof-of-concept
**4.**   Utilizing schema for date of birth (DOB) from `hmis-interop` for private profile (https://github.com/hmis-interop/logical-model/blob/FY2022-v1.0.0/src/logical-model.n3.owl#DOB)
**5.**   Included fixes for #387 where `client`, `clientProfile`, and `setClient` from `Profile`, `ProfileComponent`, `DocumentListContext`, etc. needs to be updated to `contact`, `contactProfile`, and `setContact`, respectively

Clip of Profile update with private profile:

https://github.com/codeforpdx/PASS/assets/14917816/60cfa735-b45c-40bc-9372-211b9ec4f0ed

Clip of bug fix for contacts:

https://github.com/codeforpdx/PASS/assets/14917816/e4a1e19f-cb91-402c-808e-9d6fb3b135d7

The format used for the HMIS schema follows what is instructed in the model overview documentation (https://github.com/hmis-interop/logical-model/blob/FY2022-latest/doc/HMIS-logical-model-overview.pdf, page 4)

---
### Components
- `src/components/Profile/ProfileComponents.jsx`
- `src/components/Profile/ProfileImageField.jsx`
- `src/components/Contacts/ContactListTableRow.jsx`
- `src/components/NavBar/NavMenu.jsx`

### Tests
- `test/model-helpers/Profile.test.jsx`
- `test/components/Profile/ProfileComponent.test.jsx`
- `test/components/Profile/ProfileImageField.jsx`

### Other Files
- `src/constants/rdf_predicates.js`
- `src/contexts/SignedInUserContext.jsx`
- `src/contexts/DocumentListContext.jsx`
- `src/model-helpers/Profile.js`
- `src/pages/Profile.jsx`
- `src/utils/pod-management/pod-helpers.js`

---
## Future Steps/PRs Needed to Finish This Work (optional):
- Set up permissions for private profile information
- Expand information stored in `privateProfile.ttl`
- Incorporate more HMIS definitions as part of profile
- Consolidate certain create container functions in `pod-helpers.js`

### CODE REVIEW

**Comment by leekahung** [comment]
Hey @timbot1789 and @xscottxbrownx, I've recently incorporated the new changes from the recent #362 merger with React Query and Contacts and included fixes to other locations that utilizes `Clients/Contacts` on top of the feature proposed here.

Users should be able to view other user's profile again after merging these fixes

File: src/utils/pod-management/pod-helper.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ export const createOutbox = async (session, podUrl) => {
  * @function createInbox
  * @param {Session} session - Solid's Session Object {@link Session}
  * @param {URL} podUrl - The pod URL of user
- * @returns {Promise} Promise - Generates an outbox for Pod upon log in if
+ * @returns {Promise} Promise - Generates an inbox for Pod upon log in if
```
Comment (xscottxbrownx) [inline src/utils/pod-management/pod-helper.js:104]: if this truly is inbox, then need to change the next line too

File: src/components/Profile/ProfileComponent.jsx [hunk 2]
```diff
@@ -24,21 +31,27 @@ import ProfileEditButtonGroup from './ProfileEditButtonGroup';
...
  */
-const ProfileComponent = ({ clientProfile }) => {
+const ProfileComponent = ({ contactProfile }) => {
   const { session } = useSession();
   const { updateProfileInfo, setProfileData, profileData, fetchProfileInfo } =
     useContext(SignedInUserContext);
 
+  // Public Profile Data
   const [profileName, setProfileName] = useState(profileData?.profileInfo?.profileName);
   const [nickname, setNickname] = useState(profileData?.profileInfo?.nickname);
```
Comment (xscottxbrownx) [inline src/components/Profile/ProfileComponent.jsx:41]: around here...

we have `profileData`, then either `profileInfo` or `privateProfileData`.   Could we have these consistent?  I'm assuming `profileInfo` is actually the public profile data, but could be wrong.

I guess it doesn't matter, but I would personally prefer consistency of something like:
`publicProfileInfo` and `privateProfileInfo` or the word data instead.

Comment (xscottxbrownx) [reply src/components/Profile/ProfileComponent.jsx:41]: oh we also have `profileData` and `profileDataSolid`, maybe same idea with:
`profileDataPass` and `profileDataSolid`

Comment (xscottxbrownx) [reply src/components/Profile/ProfileComponent.jsx:41]: just a thought, not the biggest deal

File: src/components/Profile/ProfileComponent.jsx [hunk 3]
```diff
@@ -58,7 +71,11 @@ const ProfileComponent = ({ clientProfile }) => {
       nickname
```
Comment (xscottxbrownx) [inline src/components/Profile/ProfileComponent.jsx:71]: same here `inputValuesPublic` and `inputValuesPrivate`

**Review by xscottxbrownx — COMMENTED** [review]
Checked file changes and look good to me, BUT I'd prefer more eyes on the `rdf predicates`, `model-helpers`, and the `tests`

---

I'm still only seeing my profile when clicking on contact name, but I am testing contacts that don't actually exist - so that's most likely the problem. Would just like confirmation of that.

I typed in random stuff when adding a contact to my list.

---

### UPDATE:
Tested ⬆️ - these same "contacts" send me to that contact page in issue-358 branch. So I believe still something wrong here.

File: src/utils/pod-management/pod-helper.js (hunk 1 above)
Comment (leekahung) [reply src/utils/pod-management/pod-helper.js:104]: This is a type, good catch!

File: src/components/Profile/ProfileComponent.jsx (hunk 2 above)
Comment (leekahung) [reply src/components/Profile/ProfileComponent.jsx:41]: Yes, `profileInfo`, `profileData` are both related to public info and `privateProfileInfo` and `privateProfileData` are both related to private info, see `fetchProfileInfo` in `src/model-helpers/Profile.js`. Public and private profile information are stored separately with distinction being the `private` prefix.

As for `profileDataSolid`, that is the updated data fetched from user's Pod in case of updates ad it pulls all data from Solid public and private hence `profileDataSolid`.

File: src/components/Profile/ProfileComponent.jsx (hunk 3 above)
Comment (leekahung) [reply src/components/Profile/ProfileComponent.jsx:71]: I believe the existing lines work to distinguish the two?

**Comment by leekahung** [comment]
> Checked file changes and look good to me, BUT I'd prefer more eyes on the `rdf predicates`, `model-helpers`, and the `tests`
> 
> I'm still only seeing my profile when clicking on contact name, but I am testing contacts that don't actually exist - so that's most likely the problem. Would just like confirmation of that.
> 
> I typed in random stuff when adding a contact to my list.
> 
> ### UPDATE:
> Tested ⬆️ - these same "contacts" send me to that contact page in issue-358 branch. So I believe still something wrong here.

As for the contact links sending you to the wrong profile, this is due to the recent merge with React Query didn't have fully incorporated the changes for all client/clients/clientProfile to contact/contacts/contactProfile, see issue #387. This branch has been fixed to send you to the proper profile if the webId exists. (see clip below)

https://github.com/codeforpdx/PASS/assets/14917816/07f4207d-14af-40e8-b958-6e859d5315e5

At the moment, if you created a link who's webId does not exist, it'll send you back to your profile with that incorrect webId as you mentioned. That is certainly a bug, but I think with the new registration flow Tim's making in PR #378 and potentially a sign-in flow in future PRs for users to link with case workers, I don't think it's too urgent of an issue. With those updates, I believe case workers don't have to manually add the webIds themselves and clients would simply need to sign up/register with a case worker and their webIds would be automatically included in the list? At least that's what I think?

File: src/components/Profile/ProfileComponent.jsx (hunk 2 above)
Comment (xscottxbrownx) [reply src/components/Profile/ProfileComponent.jsx:41]: Alright! Then I approve the way it is 😅

**Comment by xscottxbrownx** [comment]
> At the moment, if you created a link who's webId does not exist, it'll send you back to your profile with that incorrect webId as you mentioned. That is certainly a bug, but I think with the new registration flow Tim's making in PR #378 and potentially a sign-in flow in future PRs for users to link with case workers, I don't think it's too urgent of an issue. With those updates, I believe case workers don't have to manually add the webIds themselves and clients would simply need to sign up/register with a case worker and their webIds would be automatically included in the list? At least that's what I think?

Okay, just so I'm clear on the direction of the app again...

Contacts page will only be visible to organizations (maybe) and caseworkers, not clients at all correct?

AND we are not interested in giving the ability for clients to "connect with"/create contact with other clients correct? So no seeing/sharing between random friends, only clients and caseworkers/orgs?

**Comment by leekahung** [comment]
> AND we are not interested in giving the ability for clients to "connect with"/create contact with other clients correct? So no seeing/sharing between random friends, only clients and caseworkers/orgs?

Just for MVP I think.

I do think it's a good idea to be able to share things to other people if users choose to. So making the page as contacts was a good one. Makes it a kind of address book for users.

**Comment by leekahung** [comment]
> Contacts page will only be visible to organizations (maybe) and caseworkers, not clients at all correct?

From what I understand from the PR for switching to contacts instead of clients, it's meant to be universal? (See Issue #351) Except case workers and orgs have the ability to gain permission to documents and private profile information.

**Comment by xscottxbrownx** [comment]
> > AND we are not interested in giving the ability for clients to "connect with"/create contact with other clients correct? So no seeing/sharing between random friends, only clients and caseworkers/orgs?
> 
> Just for MVP I think.
> 
> I do think it's a good idea to be able to share things to other people if users choose to. So making the page as contacts was a good one. Makes it a kind of address book for users.

Ok, so does that work now - it's just not in my case because I made people up that don't exist?

**Comment by leekahung** [comment]
> Ok, so does that work now - it's just not in my case because I made people up that don't exist?

As shown from the clip I've posted in an earlier response, if the webId being used is something random and does not exist, the current behavior is to go to profile with the made up webId that leads to an empty profile card on the pod and the profile information shown on PASS will be based on your profile since the state for contact would be set to null in this case for the profile link in Contacts because profile information does not exist for this person.

**Comment by xscottxbrownx** [comment]
> > Ok, so does that work now - it's just not in my case because I made people up that don't exist?
> 
> As shown from the clip I've posted in an earlier response, if the webId being used is something random and does not exist, the current behavior is to go to profile with the made up webId that leads to an empty profile card on the pod and the profile information shown on PASS will be based on your profile since the state for contact would be set to null in this case for the profile link in Contacts because profile information does not exist for this person.

ok, that's confusing... no user will expect to click another user and see their own info.

So yeah, I guess we can chalk it up as a bug.  I guess the best thing would to not allow a user to create a contact that doesn't exist. Next best option would be to have some sort of "user does not exist" show and then redirect back to contacts page?

---

Sounds like a separate PR/Issue - got it. So now I agree with this PR and would approve if I knew more about the `model-helpers` and the test. So, I'll leave that for @timbot1789 to take a look at. 

The rest looks good to me!

**Comment by leekahung** [comment]
> ok, that's confusing... no user will expect to click another user and see their own info.

Yeah, think it's mentioned in one of the newer issues too (#386)

> So yeah, I guess we can chalk it up as a bug. I guess the best thing would to not allow a user to create a contact that doesn't exist. Next best option would be to have some sort of "user does not exist" show and then redirect back to contacts page?

Think that would be a good solution.

**Review by xscottxbrownx — APPROVED** [review]

**Comment by leekahung** [comment]
Hey @timbot1789. This should be ready for another pass. Let me know if you think it's good to merge like @xscottxbrownx.
